[package]
name = "netbox-windhcp-sync"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4.23", features = ["serde"] }
log = "0.4.17"
log4rs = "1.2.0"
serde = { version = "1.0.149", features = ["derive"] }
serde_json = "1.0.89"
serde_yaml = "0.9.14"
tokio = { version = "1.22.0", features = ["rt", "macros", "rt-multi-thread", "signal", "process"] }
warp = "0.3.3"
windows = { version = "0.43.0", features = ["Win32_System_Console", "Win32_Foundation"] }
windows-service = "0.5.0"

[dev-dependencies]
libc = "0.2.138"
