[package]
name = "netbox-windhcp-sync"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.17"
log4rs = "1.2.0"
tokio = { version = "1.22.0", features = ["rt", "macros", "rt-multi-thread"] }
warp = "0.3.3"
windows = { version = "0.43.0", features = ["Win32_System_Console", "Win32_Foundation"] }
windows-service = "0.5.0"
